apiVersion: v1
kind: Service
metadata:
  name: nginx-service-dev
  namespace: dev
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30084
      targetPort: 80
  type: NodePort

