apiVersion: v1
kind: Service
metadata:
  name: nginx-service-uat
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30083
      targetPort: 80
  type: NodePort

